#!/usr/bin/env bash
set -euo pipefail

fileTmuxBashrcConfig="$HOME/.tmux_bashrc_config"
fileBashrc="$HOME/.bashrc"

echo "---------------------------------------"
echo "Configure designated tmux nesting level"
echo "---------------------------------------"
echo
echo "0 = normal / outer tmux session"
echo "1 = first nested tmux session"
echo "2 = second nested tmux session"
echo

read -r -p "TMUX_NESTING_LEVEL [0-2]: " nestingLevel

if [[ ! "$nestingLevel" =~ ^[012]$ ]]; then
    echo "ERROR: Nesting level must be 0, 1, or 2."
    exit 1
fi

echo
echo "Creating: $fileTmuxBashrcConfig"

cat > "$fileTmuxBashrcConfig" <<EOF
# tmux designated nesting level
# Generated by $(basename -- "${BASH_SOURCE[0]}")
export TMUX_NESTING_LEVEL=$nestingLevel
EOF

# Make sure ~/.bashrc exists.
touch "$fileBashrc"

# Add the source statement only if it is not already present.
if [[ -z "$(sed -n '\|^source "\$HOME/\.tmux_bashrc_config"$|p' "$fileBashrc")" ]]; then
  echo "Adding tmux configuration source to: $fileBashrc"

  if [[ ! -s "$fileBashrc" ]]; then
    cat > "$fileBashrc" <<'EOF'
# Load tmux designated nesting level
source "$HOME/.tmux_bashrc_config"
EOF
  else
    sed -i '$a\
\
# Load tmux designated nesting level\
source "$HOME/.tmux_bashrc_config"' "$fileBashrc"
  fi
else
    echo "tmux configuration is already sourced by: $fileBashrc"
fi

echo
echo "Configured:"
echo "  TMUX_NESTING_LEVEL=$nestingLevel"
echo
echo "Start a new Bash shell or run:"
echo "  source \"$fileBashrc\""
